apiVersion: v1
kind: ConfigMap
metadata:
  name: svc-api-config
  namespace: jobsys
data:
  AWS_REGION: "us-east-1"
  ENV: "dev"
  LOG_LEVEL: "INFO"
  PORT: "8080"
  DDB_TABLE: "Jobs"
  SQS_QUEUE_URL: "http://host.minikube.internal:4566/000000000000/jobs-queue"
  AWS_ENDPOINT_URL: "http://host.minikube.internal:4566"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_DEFAULT_REGION: "us-east-1"

